use serde::{Deserialize, Serialize};

/// Enterprise application domains supported by the platform
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum EnterpriseDomain {
    CRM,
    ERP,
    HRMS,
    ECommerce,
    CrossDomain,
}

impl std::fmt::Display for EnterpriseDomain {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            EnterpriseDomain::CRM => write!(f, "CRM"),
            EnterpriseDomain::ERP => write!(f, "ERP"),
            EnterpriseDomain::HRMS => write!(f, "HRMS"),
            EnterpriseDomain::ECommerce => write!(f, "E-Commerce"),
            EnterpriseDomain::CrossDomain => write!(f, "Cross-Domain Enterprise"),
        }
    }
}

/// Intent classification of the natural language / voice request
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum QueryType {
    Distribution,
    Trend,
    Comparison,
    RootCauseAnalysis,
    Aggregation,
    DetailedList,
}

/// Structured query intent extracted from natural language / voice input
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct QueryIntent {
    pub raw_query: String,
    pub is_voice_input: bool,
    pub domain: EnterpriseDomain,
    pub query_type: QueryType,
    pub target_entities: Vec<String>,
    pub metrics: Vec<String>,
    pub time_horizon: Option<String>,
    pub filter_conditions: Vec<String>,
}

/// Database column metadata
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ColumnMetadata {
    pub name: String,
    pub data_type: String,
    pub is_nullable: bool,
    pub description: String,
}

/// Database table metadata
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TableMetadata {
    pub domain: EnterpriseDomain,
    pub table_name: String,
    pub description: String,
    pub columns: Vec<ColumnMetadata>,
    pub primary_keys: Vec<String>,
    pub foreign_keys: Vec<String>,
}

/// Full schema discovery payload returned via MCP
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SchemaMetadata {
    pub tables: Vec<TableMetadata>,
}

/// Results of executing a validated SQL query
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SqlExecutionResult {
    pub sql_query: String,
    pub columns: Vec<String>,
    pub rows: Vec<Vec<serde_json::Value>>,
    pub row_count: usize,
    pub execution_time_ms: u128,
}

/// Supported visualization types for dynamic dashboards
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum ChartType {
    PieChart,
    BarChart,
    LineChart,
    KpiCard,
    DataTable,
    AreaChart,
}

impl std::fmt::Display for ChartType {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            ChartType::PieChart => write!(f, "Pie Chart"),
            ChartType::BarChart => write!(f, "Bar Chart"),
            ChartType::LineChart => write!(f, "Line Chart"),
            ChartType::KpiCard => write!(f, "KPI Metric Card"),
            ChartType::DataTable => write!(f, "Data Table"),
            ChartType::AreaChart => write!(f, "Area Chart"),
        }
    }
}

/// Configuration spec for a visualization widget
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct VisualizationConfig {
    pub chart_type: ChartType,
    pub title: String,
    pub x_axis_label: Option<String>,
    pub y_axis_label: Option<String>,
    pub category_column: String,
    pub value_column: String,
    pub color_scheme: Vec<String>,
}

/// Single widget on a generated dashboard
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DashboardWidget {
    pub id: String,
    pub title: String,
    pub viz_type: ChartType,
    pub config: VisualizationConfig,
    pub sql_query: String,
    pub data: SqlExecutionResult,
}

/// Dynamically generated analytical dashboard
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DashboardSpec {
    pub dashboard_id: String,
    pub title: String,
    pub domain: EnterpriseDomain,
    pub query_type: QueryType,
    pub widgets: Vec<DashboardWidget>,
    pub executive_summary: String,
    pub recommendations: Vec<String>,
    pub generated_at: String,
}

/// Anomaly / factor causing business changes in root-cause analysis
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AnomalyFactor {
    pub domain: EnterpriseDomain,
    pub metric: String,
    pub change_percentage: f64,
    pub narrative: String,
}

/// Root-cause analysis payload generated by Insight Agent
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RootCauseAnalysis {
    pub primary_issue: String,
    pub observation_period: String,
    pub primary_metric_change: String,
    pub contributing_factors: Vec<AnomalyFactor>,
    pub root_cause_summary: String,
    pub actionable_recommendations: Vec<String>,
}
